CREATE TABLE "dyiflowershop_bouquet_consumables" (
	"bouquet_id" integer NOT NULL,
	"consumable_name" varchar(256) NOT NULL,
	CONSTRAINT "dyiflowershop_bouquet_consumables_bouquet_id_consumable_name_pk" PRIMARY KEY("bouquet_id","consumable_name")
);
--> statement-breakpoint
CREATE TABLE "dyiflowershop_bouquet_flowers" (
	"bouquet_id" integer NOT NULL,
	"flower_name" varchar(256) NOT NULL,
	"quantity" integer NOT NULL,
	CONSTRAINT "dyiflowershop_bouquet_flowers_bouquet_id_flower_name_pk" PRIMARY KEY("bouquet_id","flower_name")
);
--> statement-breakpoint
CREATE TABLE "dyiflowershop_bouquets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dyiflowershop_bouquets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" varchar(256) NOT NULL,
	"image" varchar(1024) NOT NULL,
	"price" real NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "dyiflowershop_row_bouquets" (
	"row_id" integer NOT NULL,
	"bouquet_id" integer NOT NULL,
	CONSTRAINT "dyiflowershop_row_bouquets_row_id_bouquet_id_pk" PRIMARY KEY("row_id","bouquet_id")
);
--> statement-breakpoint
CREATE TABLE "dyiflowershop_rows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dyiflowershop_rows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL
);
